# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

stages:
  - stage: Build
    displayName: Build and Push Docker image
    jobs:
      - job:
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DockerInstaller@0
            inputs:
              dockerVersion: '24.0.5'
          - task: Docker@2
            inputs:
              containerRegistry: 'Connection-to-ACR'
              repository: 'simple-webapp'
              command: 'buildAndPush'
              Dockerfile: '$(System.DefaultWorkingDirectory)/Dockerfile'
              tags: '$(Build.BuildNumber)'